
# API Test Cases

test_customer_1 = {
    "city_tier": "Tier 1",
    "age_group": "25-34",
    "acquisition_channel": "Instagram",
    "loyalty_tier": "Silver",
    "preferred_category": "Skin Care",
    "marketing_consent": "Yes",
    "recency_days": 30,
    "frequency_180d": 5,
    "monetary_180d": 4000,
    "return_rate_180d": 0.05,
    "avg_discount_pct_180d": 10,
    "avg_rating_180d": 4.5,
    "category_diversity_180d": 3,
    "ticket_count_90d": 0,
    "negative_ticket_rate_90d": 0.0,
    "avg_resolution_hours_90d": 0.0,
    "days_since_signup": 400,
    "sessions_30d": 12,
    "product_views_30d": 50,
    "cart_adds_30d": 6,
    "wishlist_adds_30d": 2,
    "abandoned_carts_30d": 1,
    "email_opens_30d": 5,
    "campaign_clicks_30d": 2,
    "last_visit_days_ago": 3
}

test_customer_2 = {
    "city_tier": "Tier 2",
    "age_group": "35-44",
    "acquisition_channel": "Organic",
    "loyalty_tier": "Gold",
    "preferred_category": "Makeup",
    "marketing_consent": "Yes",
    "recency_days": 160,
    "frequency_180d": 1,
    "monetary_180d": 500,
    "return_rate_180d": 0.25,
    "avg_discount_pct_180d": 30,
    "avg_rating_180d": 3.0,
    "category_diversity_180d": 1,
    "ticket_count_90d": 3,
    "negative_ticket_rate_90d": 0.5,
    "avg_resolution_hours_90d": 48,
    "days_since_signup": 150,
    "sessions_30d": 1,
    "product_views_30d": 4,
    "cart_adds_30d": 0,
    "wishlist_adds_30d": 0,
    "abandoned_carts_30d": 2,
    "email_opens_30d": 0,
    "campaign_clicks_30d": 0,
    "last_visit_days_ago": 45
}

test_customer_3 = {
    "city_tier": "Tier 3",
    "age_group": "18-24",
    "acquisition_channel": "Influencer",
    "loyalty_tier": None,
    "preferred_category": "Hair Care",
    "marketing_consent": "No",
    "recency_days": 90,
    "frequency_180d": 2,
    "monetary_180d": 1500,
    "return_rate_180d": 0.10,
    "avg_discount_pct_180d": 15,
    "avg_rating_180d": 4.0,
    "category_diversity_180d": 2,
    "ticket_count_90d": 1,
    "negative_ticket_rate_90d": 0.0,
    "avg_resolution_hours_90d": 12,
    "days_since_signup": 250,
    "sessions_30d": 5,
    "product_views_30d": 20,
    "cart_adds_30d": 2,
    "wishlist_adds_30d": 1,
    "abandoned_carts_30d": 1,
    "email_opens_30d": 1,
    "campaign_clicks_30d": 0,
    "last_visit_days_ago": 10
}
